name: Batch Build Tensorcores Wheels

on:
  workflow_dispatch:
    inputs:
      versions:
        description: 'Comma-seperated version tags of llama-cpp-python to build'
        default: 'v0.2.23,v0.2.24,v0.2.25,v0.2.26,v0.2.27,v0.2.28,v0.2.29,v0.2.30,v0.2.31,v0.2.32,v0.2.33,v0.2.34,v0.2.35,v0.2.36,v0.2.37,v0.2.38,v0.2.39,v0.2.40,v0.2.41,v0.2.42,v0.2.43,v0.2.44,v0.2.45,v0.2.46,v0.2.47,v0.2.48,v0.2.49,v0.2.50,v0.2.51,v0.2.52,v0.2.53'
        required: true
        type: string

permissions:
  contents: write
  
jobs:
  define_matrix:
    name: Define Workflow Matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    defaults:
      run:
        shell: pwsh
    env:
      PCKGVERS: ${{ inputs.versions }}
        
    steps:
      - uses: actions/checkout@v4
      
      - name: Define Job Output
        id: set-matrix
        run: |
          $x = ConvertTo-Json $env:PCKGVERS.Split(',').Trim() -Compress
          Write-Output ('matrix=' + $x) >> $env:GITHUB_OUTPUT
          
  run_workflows:
    name: Build ${{ matrix.version }} Wheels
    needs: define_matrix
    strategy:
      max-parallel: 1
      matrix:
        version: ${{ fromJSON(needs.define_matrix.outputs.matrix) }}
    uses: ./.github/workflows/build-wheels-tensorcores.yml
    with:
      version: ${{ matrix.version }}
